In [1]:
import pandas as pd

In [2]:
cities = pd.read_csv(r"C:\Users\Ā\Documents\python_class\dataset\worldcities.csv")

In [3]:
cities.head()

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
0,Tokyo,Tokyo,35.6870,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629

In [4]:
# 6. Create a DataFrame containing only cities in the United States
us_cities = cities[cities["country"] == "United States"]

print("United States cities:")
print(us_cities)

United States cities:
              city   city_ascii      lat       lng        country iso2 iso3  \
14        New York     New York  40.6943  -73.9249  United States   US  USA
33     Los Angeles  Los Angeles  34.1141 -118.4068  United States   US  USA
52         Chicago      Chicago  41.8375  -87.6866  United States   US  USA
86           Miami        Miami  25.7840  -80.2101  United States   US  USA
88         Houston      Houston  29.7860  -95.3885  United States   US  USA
...            ...          ...      ...       ...            ...  ...  ...
46496      Beecher      Beecher  43.0903  -83.7039  United States   US  USA
46497    West Earl    West Earl  40.1260  -76.1774  United States   US  USA
46505    Lewistown    Lewistown  40.5964  -77.5730  United States   US  USA
46519     Montague     Montague  42.5549  -72.5177  United States   US  USA
46562   Montpelier   Montpelier  44.2659  -72.5717  United States   US  USA

          admin_name capital  population          id
14          New York     NaN  18832416.0  1840034016
33        California     NaN  11885717.0  1840020491
52          Illinois     NaN   8489066.0  1840000494
86           Florida     NaN   6113982.0  1840015149
88             Texas     NaN   6046392.0  1840020925
...              ...     ...         ...         ...
46496       Michigan     NaN      8507.0  1840004343
46497   Pennsylvania     NaN      8507.0  1840152739
46505   Pennsylvania     NaN      8505.0  1840003592
46519  Massachusetts     NaN      8501.0  1840053435
46562        Vermont   admin      8038.0  1840002187

[5344 rows x 11 columns]

In [6]:
# US cities with population greater than 2,000,000

large_us_cities = us_cities[
    us_cities["population"] > 2000000
]

print("US cities with population greater than 2,000,000:")
print(large_us_cities)

US cities with population greater than 2,000,000:
              city     city_ascii      lat       lng        country iso2 iso3  \
14        New York       New York  40.6943  -73.9249  United States   US  USA
33     Los Angeles    Los Angeles  34.1141 -118.4068  United States   US  USA
52         Chicago        Chicago  41.8375  -87.6866  United States   US  USA
86           Miami          Miami  25.7840  -80.2101  United States   US  USA
88         Houston        Houston  29.7860  -95.3885  United States   US  USA
94          Dallas         Dallas  32.7935  -96.7667  United States   US  USA
102   Philadelphia   Philadelphia  40.0077  -75.1339  United States   US  USA
121        Atlanta        Atlanta  33.7628  -84.4220  United States   US  USA
123     Washington     Washington  38.9047  -77.0163  United States   US  USA
159         Boston         Boston  42.3188  -71.0852  United States   US  USA
179        Phoenix        Phoenix  33.5722 -112.0892  United States   US  USA
201        Detroit        Detroit  42.3834  -83.1024  United States   US  USA
215        Seattle        Seattle  47.6211 -122.3244  United States   US  USA
224  San Francisco  San Francisco  37.7558 -122.4449  United States   US  USA
256      San Diego      San Diego  32.8313 -117.1222  United States   US  USA
268    Minneapolis    Minneapolis  44.9635  -93.2678  United States   US  USA
269          Tampa          Tampa  27.9945  -82.4447  United States   US  USA
291       Brooklyn       Brooklyn  40.6501  -73.9496  United States   US  USA
297         Denver         Denver  39.7620 -104.8758  United States   US  USA
346         Queens         Queens  40.7498  -73.7976  United States   US  USA
365      Riverside      Riverside  33.9381 -117.3949  United States   US  USA
369      Las Vegas      Las Vegas  36.2333 -115.2654  United States   US  USA
379      Baltimore      Baltimore  39.3051  -76.6144  United States   US  USA
391      St. Louis      St. Louis  38.6359  -90.2451  United States   US  USA
400       Portland       Portland  45.5371 -122.6500  United States   US  USA
402    San Antonio    San Antonio  29.4632  -98.5238  United States   US  USA

               admin_name  capital  population          id
14               New York      NaN  18832416.0  1840034016
33             California      NaN  11885717.0  1840020491
52               Illinois      NaN   8489066.0  1840000494
86                Florida      NaN   6113982.0  1840015149
88                  Texas      NaN   6046392.0  1840020925
94                  Texas      NaN   5843632.0  1840019440
102          Pennsylvania      NaN   5696588.0  1840000673
121               Georgia    admin   5211164.0  1840013660
123  District of Columbia  primary   5146120.0  1840006060
159         Massachusetts    admin   4355184.0  1840000455
179               Arizona    admin   4065338.0  1840020568
201              Michigan      NaN   3716929.0  1840003971
215            Washington      NaN   3555253.0  1840021117
224            California      NaN   3364862.0  1840021543
256            California      NaN   3057778.0  1840021990
268             Minnesota      NaN   2906807.0  1840007830
269               Florida      NaN   2906035.0  1840015982
291              New York      NaN   2736074.0  1840034030
297              Colorado    admin   2691349.0  1840018789
346              New York      NaN   2405464.0  1840034002
365            California      NaN   2288508.0  1840020551
369                Nevada      NaN   2256509.0  1840020364
379              Maryland      NaN   2189589.0  1840001592
391              Missouri      NaN   2127843.0  1840001651
400                Oregon      NaN   2084045.0  1840019941
402                 Texas      NaN   2069843.0  1840022220

In [7]:
print("Number of large US cities:", len(large_us_cities))

Number of large US cities: 26

In [23]:
cities["population_millions"] = cities["population"] / 1_000_000

cities[
    ["city", "country", "population", "population_millions"]
].head()

        city    country  population  population_millions
0      Tokyo      Japan  37785000.0               37.785
1    Jakarta  Indonesia  33756000.0               33.756
2      Delhi      India  32226000.0               32.226
3  Guangzhou      China  26940000.0               26.940
4     Mumbai      India  24973000.0               24.973

In [24]:
cities.sort_values("population", ascending= False).head(10)

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id,population_millions
0,Tokyo,Tokyo,35.6870,139.7495,Japan,JP,JPN,Tōkyō,primary,37785000.0,1392685764,37.785
1,Jakarta,Jakarta,-6.1750,106.8275,Indonesia,ID,IDN,Jakarta,primary,33756000.0,1360771077,33.756
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604,32.226
3,Guangzhou,Guangzhou,23.1300,113.2600,China,CN,CHN,Guangdong,admin,26940000.0,1156237133,26.940
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629,24.973
5,Manila,Manila,14.5958,120.9772,Philippines,PH,PHL,Manila,primary,24922000.0,1608618140,24.922
6,Shanghai,Shanghai,31.2286,121.4747,China,CN,CHN,Shanghai,admin,24073000.0,1156073548,24.073
7,São Paulo,Sao Paulo,-23.5504,-46.6339,Brazil,BR,BRA,São Paulo,admin,23086000.0,1076532519,23.086
8,Seoul,Seoul,37.5667,126.9833,"Korea, South",KR,KOR,Seoul,primary,23016000.0,1410836482,23.016
9,Mexico City,Mexico City,19.4333,-99.1333,Mexico,MX,MEX,Ciudad de México,primary,21804000.0,1484247881,21.804

In [25]:
cities["country"].value_counts().head(15)

country
India             7108
United States     5344
Brazil            2961
Germany           1759
China             1732
Philippines       1584
United Kingdom    1365
Italy             1357
Japan             1344
France            1160
Russia            1059
Mexico            1014
Madagascar         832
Spain              783
Colombia           732
Name: count, dtype: int64

In [26]:
cities["population"].value_counts().head(10)

population
10000.0    154
15000.0     90
9000.0      78
12000.0     68
13000.0     64
20000.0     60
11000.0     52
30000.0     46
10.0        45
25000.0     42
Name: count, dtype: int64

In [27]:
cities.columns

Index(['city', 'city_ascii', 'lat', 'lng', 'country', 'iso2', 'iso3',
       'admin_name', 'capital', 'population', 'id', 'population_millions'],
      dtype='str')

In [28]:
mean_population_by_country = (
    cities
    .groupby("country")["population"]
    .mean()
    .sort_values(ascending=False)
)

mean_population_by_country.head(15)

country
Singapore               5.983000e+06
China                   7.939591e+05
Kuwait                  7.343922e+05
United Arab Emirates    6.434473e+05
Korea, South            5.974348e+05
Macau                   5.687000e+05
Nigeria                 5.591923e+05
Hong Kong               5.327502e+05
Sudan                   4.353858e+05
Bangladesh              3.878777e+05
Saudi Arabia            3.706994e+05
Indonesia               3.550121e+05
Malaysia                3.418106e+05
Korea, North            3.172870e+05
Egypt                   3.088498e+05
Name: population, dtype: float64

In [29]:
indian_cities = cities[cities["country"] == "India"]
indian_cities.shape

(7108, 12)

In [21]:
indian_cities

,city,city_ascii,lat,lng,country,iso2,iso3,admin_name,capital,population,id
2,Delhi,Delhi,28.6100,77.2300,India,IN,IND,Delhi,admin,32226000.0,1356872604
4,Mumbai,Mumbai,19.0761,72.8775,India,IN,IND,Mahārāshtra,admin,24973000.0,1356226629
10,Kolkāta,Kolkata,22.5675,88.3700,India,IN,IND,West Bengal,admin,21747000.0,1356060520
21,Bangalore,Bangalore,12.9789,77.5917,India,IN,IND,Karnātaka,admin,15386000.0,1356410365
29,Chennai,Chennai,13.0825,80.2750,India,IN,IND,Tamil Nādu,admin,12395000.0,1356374944
...,...,...,...,...,...,...,...,...,...,...,...
47879,Jaitpura,Jaitpura,26.9231,75.8080,India,IN,IND,Rājasthān,NaN,NaN,1356971126
47880,Rājapālaiyam,Rajapalaiyam,9.4204,77.5800,India,IN,IND,Tamil Nādu,NaN,NaN,1356110350
47881,Navsāri,Navsari,20.8504,72.9200,India,IN,IND,Gujarāt,NaN,NaN,1356120513
47882,Tonk,Tonk,26.1505,75.7900,India,IN,IND,Rājasthān,NaN,NaN,1356991408
47883,Hubli,Hubli,15.3550,75.1362,India,IN,IND,Karnātaka,NaN,NaN,1356102365

In [30]:
indian_cities.columns

Index(['city', 'city_ascii', 'lat', 'lng', 'country', 'iso2', 'iso3',
       'admin_name', 'capital', 'population', 'id', 'population_millions'],
      dtype='str')

In [33]:
indian_cities["admin_name"].value_counts().head(15)

admin_name
Bihār             1405
Andhra Pradesh    1064
Tamil Nādu        1061
Kerala             650
Karnātaka          491
Madhya Pradesh     429
West Bengal        320
Uttar Pradesh      239
Punjab             214
Mahārāshtra        212
Gujarāt            202
Rājasthān          148
Jhārkhand          138
Odisha              99
Haryāna             78
Name: count, dtype: int64

In [34]:
indian_cities.groupby("admin_name")["population"].mean().sort_values(
    ascending=False
).head(15)

admin_name
Telangāna                      1.049400e+07
Delhi                          2.240205e+06
Mahārāshtra                    2.973980e+05
Chhattīsgarh                   2.258690e+05
Uttar Pradesh                  1.702491e+05
Gujarāt                        1.557085e+05
Haryāna                        1.363635e+05
West Bengal                    1.255200e+05
Tripura                        1.094483e+05
Rājasthān                      1.041786e+05
Puducherry                     1.009726e+05
Mizoram                        9.280812e+04
Uttarākhand                    8.675486e+04
Andaman and Nicobar Islands    8.280533e+04
Assam                          7.443191e+04
Name: population, dtype: float64

In [35]:
cities.isna().sum()

city                       0
city_ascii                 2
lat                        0
lng                        0
country                    0
iso2                      33
iso3                       0
admin_name               201
capital                32921
population               251
id                         0
population_millions      251
dtype: int64

In [ ]:
indian_cities.to_csv